### ISSUE TITLE
请教大佬关于图片链接的相关问题。

### ISSUE THREAD

**Issue by Swor-dart** [anosu/shuffle-img-api#1]
请求大佬能不能分享一下图片的txt，我打算全部下载下来放到个人服务器上，我知道可能很冒昧，大佬可能也收集了很久，很喜欢大佬的这些图片，想放到自己的随机图API里，大佬能否分享一下呢？大佬可以分享后，我再回复后关闭这个issure，如果不能的话，也对大佬的api表示感谢。

**Comment by Swor-dart** [comment]
![image](https://user-images.githubusercontent.com/77768361/193412040-df770444-58d1-4493-8cd7-62f2ed7dfc65.png)
另外请问是否只需要php代码和存放图片链接的txt文件夹呢？

**Comment by anosu** [comment]
只需要php和txt文件。关于txt文件，有一部分是我朋友的，不便分享，不过我自己传的3000张1080p的图片可以分享，文件已经放在了仓库的txt目录下https://github.com/anosu/shuffle-img-api/blob/main/txt/pc.txt
